### ISSUE TITLE
URL endpoints for CIM documents

### ISSUE THREAD

**Issue by Sondergaard** [Energinet-DataHub/geh-api-gateway#22]
## Description

A major part of the system is the ability to receive data from market actors. The scope is restrict to receive `CIM XML` via the HTTP protocol. The endpoints can be divided into two categories - sending data and downloading data to/from the system.

This feature enable us to perform a test with external parties. The scope for the test is grid operators and it will take place in start Jan. 2022. The endpoints are defined and documented with `RPC` terms - implying that you are invoking / starting a business process in a remote system.

### Sending data to the system

The proposal from market actors is that an endpoint indicates what document it supports receiving. This means that an endpoint name contains `document name` as part of the URL. The benefit from a system perspective is that routing of data can be based on the URL to the destination domain.

Eg.:

- <https://b2b.datahub.dk/cim/requestchangeofsupplier>
- <https://b2b.datahub.dk/cim/accountingpointcharacteristics>

### Download data from the system

The market actors would prefer to have separate `queue` per document group. Document groups could be `Timeseries`, `Masterdata`, `Charges` etc.

## Acceptance Criteria

- [ ] An appropriate content type is required - we support application/xml from the start
- [ ] Endpoints needed for each `product team` is created
- [ ] Endpoints are document in a consistent manner with samples

**Comment by Renetnielsen** [comment]
- [ ] We validate that the 'Content-Type' header is `application/xml`
- [ ] We expose the endpoints for the following RSM messages:
  - https://b2b.datahub.dk/cim/??
- [ ] We forward each request to the respective domains listed below:
  - https://b2b.datahub.dk/cim/?? -> Team ??
- [ ] Endpoints are documented in a consistent manner
- [ ]
